### ISSUE TITLE
Build runner does not update the generated code if some queries are modified, until the build folder folder in .dart_tool is deleted.

### ISSUE THREAD

**Issue by namanshergill** [comigor/artemis#317] opened 2021-06-05 13:55 UTC
## Bug 
If the build runner was run to generate the code for, say,
```grapqhl
query test{
    item{
        id
    }
}
```
But then afterwards the query is modified to be
```grapqhl
query test{
    item{
        id
        value
    }
}
```

If the build runner is run again, the new generated code will be based on the previous query and would not include the `value` field. The only way to make it use the latest queries is to delete the build folder before the files are generated.

## Specs
Artemis version: 
7.0.0-beta.11

  
<summary>Artemis output:</summary>
  
```bash
[  +96 ms] executing: [C:\Users\Naman\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +584 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[   +1 ms] executing: [C:\Users\Naman\flutter/] git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[  +89 ms] Exit code 0 from: git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[        ] 2.2.0
[   +7 ms] executing: [C:\Users\Naman\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Naman\flutter/] git ls-remote --get-url origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +160 ms] executing: [C:\Users\Naman\flutter/] git rev-parse --abbrev-ref HEAD
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +103 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +34 ms] executing: C:\Users\Naman\flutter\bin\cache\dart-sdk\bin\pub.bat run build_runner watch --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 659ms

[WARNING] build.fallback:
The package `dio_hub` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] Watch:Setting up file watchers...
[INFO] Watch:Setting up file watchers completed, took 7ms

[INFO] Watch:Waiting for all file watchers to be ready...
[INFO] Watch:Waiting for all file watchers to be ready completed, took 878ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 121ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.5s

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 39ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 105ms

[INFO] Build:Succeeded after 156ms with 0 outputs (0 actions)


```
</details>

**Comment by vasilich6107** [comment] 2021-06-06 16:18
I’m not sure that this is somehow related to Artemis.
Personally I use Artemis nearly 18 month in a row and did not experience any similar issues.
This could be caused by local environment issues and build_runner library issues.

I’m using MacOS, so I will not be able even to reproduce your issues.

**Comment by namanshergill** [comment] 2021-06-06 16:30
> I’m not sure that this is somehow related to Artemis.
> Personally I use Artemis nearly 18 month in a row and did not experience any similar issues.
> This could be caused by local environment issues and build_runner library issues.
> 
> I’m using MacOS, so I will not be able even to reproduce your issues.

I thought so too, initially, but this happening only with Artemis. Other libraries (For instance, auto_route) that also generate code reflect the changes immediately without having to delete the build folder.

**Comment by vasilich6107** [comment] 2022-03-30 16:49
Will close this issue for now as far as there is no clear understanding how to reproduce it

**Closed as completed by vasilich6107** 2022-03-30 16:49 UTC
Labels: bug
