### ISSUE TITLE
[Question] Performance tips for build times

### ISSUE THREAD

**Issue by Grohden** [comigor/artemis#181] opened 2020-07-08 12:50 UTC
Been using artemis `6.4.4-beta.1` and getting longer build times as I add new graphql files, I'm unsure if it's expected or if there's something that I can do to improve these build times. 

Currently I have:
* 17 files with one fragment each 
* 20 files with one query each
* 4 files with one mutation each
* A graphql schema with 7K lines.

Here's a example build log:
```
➜  quirons git:(feature/new-sublists) ✗ flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 475ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 129ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 937ms

[INFO] Running build...
[INFO] 10m 4s elapsed, 0/1 actions completed.
[WARNING] No actions completed for 10m 4s, waiting on:
  - artemis:artemis on lib/$lib$

[INFO] 10m 5s elapsed, 1/17 actions completed.
[INFO] 10m 6s elapsed, 1/17 actions completed.
[INFO] 10m 7s elapsed, 1/17 actions completed.
[INFO] 10m 8s elapsed, 1/17 actions completed.
[INFO] 10m 9s elapsed, 1/17 actions completed.
[INFO] 10m 14s elapsed, 1/17 actions completed.
[INFO] 10m 20s elapsed, 2/17 actions completed.
[INFO] 10m 21s elapsed, 26/38 actions completed.
[INFO] 10m 22s elapsed, 39/44 actions completed.
[INFO] Running build completed, took 10m 23s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 97ms

[INFO] Succeeded after 10m 23s with 3 outputs (46 actions)
```

<details>
  <summary>Here's my `build.yaml` for ref</summary>

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - always_put_required_named_parameters_first
            - constant_identifier_names
            - lines_longer_than_80_chars
            - prefer_const_literals_to_create_immutables
      icomoon_selection_gen:
        generate_for:
          - lib/assets/icons/selection.json
        options:
          font_name: Icomoon
      artemis:
        options:
          scalar_mapping:
            - custom_parser_import: 'package:quirons/graphql/coercers.dart'
              graphql_type: DateTime
              dart_type: DateTime
          fragments_glob: lib/graphql/fragments/*.graphql
          # Prefix every output with .graphql.dart to avoid
          # generating a useless file
          schema_mapping:
            - schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/{queries,mutations}/*.graphql
              output: lib/graphql/gen/api.graphql.dart
              naming_scheme: pathedWithFields
```
</details>

So here's my question: Is there anything I can do - or that I'm doing wrong - to improve these build times?

**Comment by vasilich6107** [comment] 2020-07-16 18:32
Hi. I did not have such long build time ever.
10 minutes is very long.
If you create a dummy project which reproduces the build time on your machine I'll try to run it locally.
May be we could find something...

**Comment by Grohden** [comment] 2020-07-16 19:27
@vasilich6107 
Sure, here's the repo
https://github.com/Grohden/artemis-perf-issue-code

**Comment by vasilich6107** [comment] 2020-07-17 07:38
Hmmm. It's definitely building way too long...
I suppose this is caused by the schema size.
Performing additional checks

**Comment by vasilich6107** [comment] 2020-07-17 07:43
If you add `--verbose` flag to the run command you'll see that it is not "wainig" it has a lot of code to build.
May be we will find some some approach to improve the performance

**Comment by vasilich6107** [comment] 2020-07-17 08:39
check `canonical-performance` branch, PR is awaiting to be merged.
It shows `[INFO] Build:Succeeded after 1m 10s with 3 outputs (6 actions)`

**Comment by Grohden** [comment] 2020-07-17 12:02
@vasilich6107 
Thank you! `canonical-performance` worked like a charm in the original project!

`[INFO] Succeeded after 52.1s with 4 outputs (159 actions)`

**Comment by vasilich6107** [comment] 2020-07-17 13:16
PR merged, awaiting for release.

**Closed by vasilich6107** 2020-07-17 13:16 UTC
